# Generated by Django 3.2.8 on 2021-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
